export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";

export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const FETCH_CHANNEL = "FETCH_CHANNEL";

export const CREATE_CHANNELS = "CREATE_CHANNELS";

//export const FETCH_CHANNEL_MESSAGES = "FETCH_CHANNEL_MESSAGES";

export const POST_MESSAGE = "POST_MESSAGE";
export const FETCH_MESSAGES = "FETCH_MESSAGES";

export const SET_CHANNELS_LOADING = "SET_CHANNELS_LOADING";
export const SET_MESSAGES_LOADING = "SET_MESSAGES_LOADING";

export const CREATE_CHANNEL = "CREATE_CHANNEL";

